name: chirpneighbor_backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - FastAPI
  - scipy
  - scikit-learn
  - librosa
  - uvicorn
  - python-dotenv
  - pyyaml
  - sqlmodel
  - aiosqlite
  - alembic
  - websockets
  - pip
  - pip: 
    - birdnetlib
    - soundfile
